# Generated by Django 4.0 on 2022-01-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_customuser_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('username', models.TextField(blank=True, default='', null=True)),
                ('password', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=265)),
                ('last_name', models.CharField(max_length=265)),
                ('address', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
