# Generated by Django 4.0 on 2022-01-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_alter_staffs2_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='students2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, default='', null=True)),
                ('password', models.TextField(blank=True, default='', null=True)),
                ('first_name', models.CharField(max_length=265)),
                ('last_name', models.CharField(max_length=265)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
