# Generated by Django 4.0 on 2022-01-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_students2'),
    ]

    operations = [
        migrations.AddField(
            model_name='students2',
            name='course',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='students2',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='male', max_length=200),
        ),
        migrations.AddField(
            model_name='students2',
            name='profile_pic',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
