# Generated by Django 4.0 on 2022-01-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_courses2_subjects2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects2',
            name='course',
        ),
        migrations.AddField(
            model_name='subjects2',
            name='course_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='subjects2',
            name='staff',
            field=models.TextField(default=''),
        ),
    ]
